name: dart_packages

packages:
  - packages/sign_in_with_apple/*

scripts:
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: Build all generated files for Dart & Flutter packages in this project.

  test:
    run: melos exec --dir-exists=test --fail-fast -- "flutter test --test-randomize-ordering-seed random"
    description: Run Flutter tests for a specific package in this project.

  test:ci:
    run: melos exec --dir-exists=test --fail-fast -- "flutter test --concurrency 4 --coverage --test-randomize-ordering-seed random"
    description: Run Flutter tests for a specific package in this project and generate a coverage report.

  format:
    run: melos exec -- "dart fix --apply ; dart format ."
    description: Format all Dart files in this project.

  format:ci:
    run: melos exec -- "dart format . --set-exit-if-changed"
    description: Check Dart file formatting for all packages in this project.
