include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    comment_references: true
    diagnostic_describe_all_properties: false

    avoid_print: true
    always_specify_types: false
    avoid_types_on_closure_parameters: false
    omit_local_variable_types: true
    avoid_annotating_with_dynamic: false
    avoid_dynamic_calls: true

    prefer_final_parameters: false
    avoid_final_parameters: true
    prefer_final_locals: true
    unnecessary_final: false
    no_leading_underscores_for_local_identifiers: true

    always_use_package_imports: true
    prefer_relative_imports: false

    prefer_single_quotes: true
    prefer_double_quotes: false

    always_put_required_named_parameters_first: false
    avoid_positional_boolean_parameters: false

    avoid_catches_without_on_clauses: false
    prefer_expression_function_bodies: false
    sort_pub_dependencies: true
    directives_ordering: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    require_trailing_commas: true

    no_default_cases: true
    prefer_asserts_with_message: true

    constant_identifier_names: false
    prefer_const_constructors_in_immutables: true
    empty_constructor_bodies: true

    prefer_mixin: true
    avoid_classes_with_only_static_members: false

    use_build_context_synchronously: false
    discarded_futures: true
